arr = [
  "ALTER SEQUENCE public.Abbrevations_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.All_verbs_theme_model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.apihitlog_id_seq RESTART WITH",
  "ALTER SEQUENCE public.apihitlog_CE_id_seq RESTART WITH",
  "ALTER SEQUENCE public.APISource_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ApplicationRole_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ApplicationsUsers_id_seq RESTART WITH",
  "ALTER SEQUENCE public.BatchUploadHistory_id_seq RESTART WITH",
  "ALTER SEQUENCE public.BlackList_id_seq RESTART WITH",
  "ALTER SEQUENCE public.BlacklistToken_id_seq RESTART WITH",
  "ALTER SEQUENCE public.BleepingComputerComScriptInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ClientExternalSearchInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ClientJobs_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ClientJobsFileMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ClientJobsFileMapping_Bkp_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ClientJobsFileMapping_bkp_20Jan23_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CognitoUsers_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CommentDropDownLayer1_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CommentDropDownLayer2_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CommentDropDownLayer3_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Common_titles_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.common_words_lemma_spacy_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Common_words_v2_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CompanyProfiles_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CompanyProfiles_bkp_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CompanyProfiles_Check_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CompanyProfilesBKP14Jan2022_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CompanyProfilesDemoReady_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CompanyProfilesInitiated_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CompanyType_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Content_Extraction_Output_Stats_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ContentExtractionAPIStatus_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CountryDetails_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Criticality_id_seq RESTART WITH",
  "ALTER SEQUENCE public.CriticalityScore_id_seq RESTART WITH",
  "ALTER SEQUENCE public.DAAssociationMapBasicData_id_seq RESTART WITH",
  "ALTER SEQUENCE public.DataBreachScriptInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.DateLinkDateIssue_id_seq RESTART WITH",
  "ALTER SEQUENCE public.DecisionParameter_id_seq RESTART WITH",
  "ALTER SEQUENCE public.dedupe_status_id_seq RESTART WITH",
  "ALTER SEQUENCE public.EntityScheduledMonitoring_id_seq RESTART WITH",
  "ALTER SEQUENCE public.EntitySpecificUserDocuments_id_seq RESTART WITH",
  "ALTER SEQUENCE public.EntitySpecificUserNotes_id_seq RESTART WITH",
  "ALTER SEQUENCE public.EntityWiseAssociationMapURL_id_seq RESTART WITH",
  "ALTER SEQUENCE public.EventCriticality2_id_seq RESTART WITH",
  "ALTER SEQUENCE public.EventList_id_seq RESTART WITH",
  "ALTER SEQUENCE public.FAQ_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Final_framework_projects_theme_model_DS2_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Final_framework_projects_theme_model_DS3_id_seq RESTART WITH",
  "ALTER SEQUENCE public.FinancialType_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Frequency_weights_theme_model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.GroupingModified_Pilot_April13_2021_id_seq RESTART WITH",
  "ALTER SEQUENCE public.IndividualProfile_id_seq RESTART WITH",
  "ALTER SEQUENCE public.InvestingComScriptInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.InvestingComScriptInput_bkp_id_seq RESTART WITH",
  "ALTER SEQUENCE public.InvestingComScriptInput_Bkp1_id_seq RESTART WITH",
  "ALTER SEQUENCE public.InvestingNewsLinks_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Invitation_id_seq RESTART WITH",
  "ALTER SEQUENCE public.keywords_id_seq RESTART WITH",
  "ALTER SEQUENCE public.keywords_aml_id_seq RESTART WITH",
  "ALTER SEQUENCE public.KeywordsEvents_id_seq RESTART WITH",
  "ALTER SEQUENCE public.KeywordsEvents_14March2022_id_seq RESTART WITH",
  "ALTER SEQUENCE public.KeywordsEvents_14March2022_v2_id_seq RESTART WITH",
  "ALTER SEQUENCE public.KeywordsEvents_15March2022_id_seq RESTART WITH",
  "ALTER SEQUENCE public.KeywordsEvents_HR1_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Legal_Extensions_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.LinkFlag_id_seq RESTART WITH",
  "ALTER SEQUENCE public.LinkIdProcessed_id_seq RESTART WITH",
  "ALTER SEQUENCE public.LinkLogging_id_seq RESTART WITH",
  "ALTER SEQUENCE public.links_process_status_id_seq RESTART WITH",
  "ALTER SEQUENCE public.links_process_status_bkp_Apr_05_2021_id_seq RESTART WITH",
  "ALTER SEQUENCE public.links_processed_datafields_id_seq RESTART WITH",
  "ALTER SEQUENCE public.LinkSpecificNotes_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Logger_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Manual_NewsLink_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ManualLinkDateIssue_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Model_Path_theme_model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ner_status_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NER_Table_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewDatePublished_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsAllocation_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsExtractionStatus_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsLink_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsLink_86_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsLink_ClientLinks_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsLink_grouping_test_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsLink_P21_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsMonitoring_id_seq RESTART WITH",
  "ALTER SEQUENCE public.NewsSource_id_seq RESTART WITH",
  "ALTER SEQUENCE public.PricingPlan_id_seq RESTART WITH",
  "ALTER SEQUENCE public.PriorityKeywordsList_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Probability_weights_theme_model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ProgressNotification_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Project_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ProjectAPIMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ProjectMonitoringData_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ProjectNewsSourceMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.projectTilteMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ProjectType_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ProjectTypeDisplayItemMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ProjectWiseNewsImage_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Pronouns_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ReadySearchStrings_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Relevance_model_user_input_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.relevance_sentiment_keywords_status_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ReviewStatus_id_seq RESTART WITH",
  "ALTER SEQUENCE public.rss_master_input_id_seq RESTART WITH",
  "ALTER SEQUENCE public.RSSDatabreachesLinks_id_seq RESTART WITH",
  "ALTER SEQUENCE public.RSSFeedScriptInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.RSSNewsLinks_id_seq RESTART WITH",
  "ALTER SEQUENCE public.RSSNewsLinks_Bkp1_id_seq RESTART WITH",
  "ALTER SEQUENCE public.RSSNewsLinks11_id_seq RESTART WITH",
  "ALTER SEQUENCE public.RSSNewsLinks111_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SampleFile_id_seq RESTART WITH",
  "ALTER SEQUENCE public.scripts_status_log_id_seq RESTART WITH",
  "ALTER SEQUENCE public.scripts_status_log_bkp_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Search_Language_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Search_Language_Backup_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Search_Monitoring_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Search_TimeFrame_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Search_Type_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SearchParameter_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SearchStringFormat_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SearchStringFormatMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SearchTerm_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SearchTermCategory_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SearchTermMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SearchTermRating_id_seq RESTART WITH",
  "ALTER SEQUENCE public.source_reputation_domain_id_seq RESTART WITH",
  "ALTER SEQUENCE public.stopwords_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.subscription_id_seq RESTART WITH",
  "ALTER SEQUENCE public.SummarizationTable_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Support_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_association_map_themes_events_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_content_extracted_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_content_extracted_translation_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_content_extracted_translation_Translated_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_content_extraction_tobe_processed_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_grouping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_keywords_themes_events_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_ner_extraction_tobe_processed_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_ner_extraction_tobe_processed_check_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_relevance_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_relevance_sentiment_keywords_tobe_processed_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_sentiment_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_source_reputation_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_summary_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_summary_to_be_processed_id_seq RESTART WITH",
  "ALTER SEQUENCE public.t_tags_ner_id_seq RESTART WITH",
  "ALTER SEQUENCE public.TargetEntity_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Team_id_seq RESTART WITH",
  "ALTER SEQUENCE public.TeamUserMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Temp_JobStatus_LinkExtraction_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Temp_MasterInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Temp_MasterOutput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.temp_newslink_Nitin_1_id_seq RESTART WITH",
  "ALTER SEQUENCE public.temp_NewsLink_relevancescore_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Temp_RSSFeedScriptInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Test_MasterInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Test_MasterOutput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Test_NewsLink_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Test_RSSDatabreachesLinks_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Test_RSSFeedScriptInput_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Test_RSSNewsLinks_id_seq RESTART WITH",
  "ALTER SEQUENCE public.ThemeList_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Thresholds_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.UIDisplayItems_id_seq RESTART WITH",
  "ALTER SEQUENCE public.Url_id_seq RESTART WITH",
  "ALTER SEQUENCE public.UserNotes_id_seq RESTART WITH",
  "ALTER SEQUENCE public.UserProjectRoleMapping_id_seq RESTART WITH",
  "ALTER SEQUENCE public.UserSpecificDayCount_id_seq RESTART WITH",
  "ALTER SEQUENCE public.v2Common_titles_Relevance_Model_DS_id_seq RESTART WITH",
  "ALTER SEQUENCE public.WhiteList_id_seq RESTART WITH",
];

num = [
  "15",
  "5163",
  "463776",
  "1",
  "1",
  "5",
  "67",
  "114",
  "11",
  "1269",
  "1",
  "134",
  "59978",
  "90924",
  "1",
  "1",
  "1",
  "15",
  "20",
  "184",
  "1",
  "172",
  "39522",
  "74757",
  "1",
  "1",
  "1",
  "1",
  "27548",
  "3",
  "1",
  "5710",
  "241",
  "4",
  "4",
  "6",
  "4",
  "1",
  "42",
  "1",
  "1",
  "1",
  "172",
  "1",
  "315",
  "2045",
  "1",
  "1",
  "7449",
  "3",
  "6",
  "1",
  "49",
  "1",
  "1",
  "1",
  "7",
  "1",
  "1",
  "21306",
  "50462",
  "1",
  "1",
  "1",
  "1",
  "2194",
  "5",
  "1464439",
  "1",
  "1",
  "1",
  "1",
  "7",
  "17182",
  "1",
  "222",
  "2",
  "1",
  "2",
  "2915",
  "1",
  "1",
  "1176",
  "1",
  "1",
  "1",
  "1",
  "1",
  "55",
  "2",
  "1",
  "5",
  "85870",
  "50",
  "1",
  "42",
  "746",
  "13",
  "4",
  "1226",
  "61",
  "3",
  "1",
  "3",
  "1",
  "4",
  "1",
  "1",
  "1755",
  "1",
  "1",
  "1",
  "1",
  "3",
  "248018",
  "1",
  "243",
  "1",
  "9",
  "8",
  "3",
  "1",
  "3",
  "3",
  "120363",
  "1",
  "1",
  "1",
  "15146",
  "172",
  "2",
  "3",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "267",
  "1361992",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "1",
  "274",
  "20",
  "43",
  "6",
  "1",
  "116",
  "165",
  "193",
  "1",
];

ans = [];
for (i = 0; i < num.length; i++) {
  ans[i] = arr[i] + " " + num[i];
}

// get the Console class
const { Console } = require("console");
// get fs module for creating write streams
const fs = require("fs");

// make a new logger
const myLogger = new Console({
  stdout: fs.createWriteStream("normalStdout.txt"),
  stderr: fs.createWriteStream("errStdErr.txt"),
});

// saving to normalStdout.txt file
for (i = 0; i < num.length; i++) {
  myLogger.log(ans[i]);
}
